---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-deployer-data
  namespace: splunk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-deployer-config
  namespace: splunk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

