---
apiVersion: v1
kind: Service
metadata:
  name: license-master
  #namespace: splunk
  labels:
    app: splunk
    tier: management
spec:
  #type: LoadBalancer
  selector:
    app: splunk
    role: splunk_license_master
  ports:
    - name: splunkweb
      port: 8000
      targetPort: 8000
    - name: splunkd
      port: 8089
      targetPort: 8089
  clusterIP: None
