---
apiVersion: v1
kind: Service
metadata:
  name: indexer 
  #namespace: splunk
  labels:
    app: splunk
    tier: idxcluster 
spec:
  #type: LoadBalancer
  selector:
    app: splunk
    role: splunk_indexer
  ports:
    - name: splunkweb
      port: 8000
      targetPort: 8000
    - name: splunkd
      port: 8089
      targetPort: 8089
    - name: replication
      port: 4001 
      targetPort: 4001
    - name: s2s
      port: 9997
      targetPort: 9997
  clusterIP: None
