---
retry_num: 50
splunk:
  app_paths:
    default: /opt/splunk/etc/apps
    httpinput: /opt/splunk/etc/apps/splunk_httpinput
    idxc: /opt/splunk/etc/master-apps
    shc: /opt/splunk/etc/shcluster/apps
  exec: /opt/splunk/bin/splunk
  group: splunk
  hec_disabled: 0
  hec_enableSSL: 1
  hec_port: 8088
  hec_token: 6af192bf-c834-45dc-811a-81ff544fd838
  home: /opt/splunk
  http_port: 8000
  idxc:
    enable: true 
    label: idxc_label
    replication_factor: 3
    replication_port: 4001
    search_factor: 3
    secret: qnGJdjQbpZqs7BXMXEq5K3TBqg1uuntX
  opt: /opt
  password: Mph/RPvFaoyhkue7nqu0ZGP0yoDBHjcP
  pid: /opt/splunk/var/run/splunk/splunkd.pid
  s2s_port: 9997
  shc:
    enable: true 
    label: shc_label
    replication_factor: 3
    replication_port: 4001
    secret: Ms96wbaEK/8gckJqrnRMtoxT70JAOx0x
  svc_port: 8089
  user: splunk

